xrow_rest_api:
    path: /user
    defaults: 
        _controller: xrow_rest.controller.api:userAction
    methods: [POST]
    
xrow_rest_api_articles:
    path: /articles
    defaults: 
        _controller: xrow_rest.controller.api:articlesAction
    methods: [GET]