xrowapi_user:
    path: /user
    defaults: 
        _controller: xrow_rest.controller.api:getUserAction
    methods: [GET]

xrowapi_account:
    path:     /account
    defaults:
        _controller: xrow_rest.controller.api:getAccountAction
    methods: [GET]

xrowapi_subscriptions:
    path:     /subscriptions
    defaults:
        _controller: xrow_rest.controller.api:getSubscriptionsAction
    methods: [GET]

xrowapi_logout:
    path:     /logout
    defaults:
        _controller: xrow_rest.controller.api:logoutAction
    methods: [GET]