xrow_rest_api_auth:
    path:   /auth
    defaults: 
        _controller: xrowRestBundle:Api:setAuthentication
    methods: [GET|POST]

xrowapi_user:
    path:   /user
    defaults: 
        _controller: xrowRestBundle:Api:getUser
    methods: [GET|PATCH]

xrowapi_account:
    path:   /account
    defaults:
        _controller: xrowRestBundle:Api:getAccount
    methods: [GET]

xrowapi_subscriptions:
    path:   /subscriptions
    defaults:
        _controller: xrowRestBundle:Api:getSubscriptions
    methods: [GET]

xrowapi_subscription:
    path: /subscription/{subscriptionId}
    defaults: 
        _controller: xrowRestBundle:Api:getSubscription
    methods: [GET]

xrowapi_checkpassword:
    path:   /checkpassword
    defaults:
        _controller: xrowRestBundle:Api:checkPassword
    methods: [GET]

xrowapi_logout:
    path:   /logout
    defaults:
        _controller: xrowRestBundle:Api:logout
    methods: [DELETE]

xrowapi_session:
    path:   /session
    defaults:
        _controller: xrowRestBundle:Api:getSession
    methods: [GET|POST]