xrow_rest_api_auth:
    path:   /auth
    defaults: 
        _controller: xrowRestBundle:Api:setAuthentication
    methods: [GET|POST]

xrowapi_user:
    path:   /user
    defaults: 
        _controller: xrowRestBundle:Api:getUser
    methods: [GET|PATCH|OPTIONS]

xrowapi_account:
    path:   /account
    defaults:
        _controller: xrowRestBundle:Api:getAccount
    methods: [GET]

xrowapi_subscriptions:
    path:   /subscriptions
    defaults:
        _controller: xrowRestBundle:Api:getSubscriptions
    methods: [GET]

xrowapi_subscription:
    path: /subscription/{subscriptionId}
    defaults: 
        _controller: xrowRestBundle:Api:getSubscription
    methods: [GET]

xrowapi_checkpassword:
    path:   /checkpassword
    defaults:
        _controller: xrowRestBundle:Api:checkPassword
    methods: [GET]

xrowapi_session_delete:
    path: /sessions/{sessionId}
    defaults:
        _controller: xrowRestBundle:Api:deleteSession
    methods: [DELETE|OPTIONS|GET]

xrowapi_session_get:
    path: /session
    defaults:
        _controller: xrowRestBundle:Api:getSession
    methods: [GET|POST]

xrowapi_accountActiveInfo:
    path: /accountactiveinfo
    defaults: 
        _controller: xrowRestBundle:Api:accountActiveInfo
    methods: [POST]