parameters:
    xrow_rest.controller.user.class: xrow\restBundle\Controller\User
    xrow.oauth.user_provider.class: xrow\restBundle\OAuth\UserProvider

services:
    xrow_rest.controller.user:
        class: %xrow_rest.controller.user.class%
        parent: ezpublish_rest.controller.base

    xrow.oauth.user_provider:
        class: %xrow.oauth.user_provider.class%
        arguments:
            - @doctrine
