parameters:
    xrow_rest.controller.user.class: xrow\restBundle\Controller\User
    xrow_rest.controller.crmplugin.class: xrow\restBundle\Controller\CRMPlugin
 
services:
    xrow_rest.controller.user:
        class: %xrow_rest.controller.user.class%
        parent: ezpublish_rest.controller.base

    xrow_rest.controller.crmplugin:
        class: %xrow_rest.controller.crmplugin.class%
