parameters:
    xrow_rest.controller.user.class: Xrow\Bundle\RestBundle\Controller\User
 
services:
    xrow_rest.controller.user:
        class: %xrow_rest.controller.user.class%
        parent: ezpublish_rest.controller.base
        arguments:
            - @ezpublish.api.service.user
            - @ezpublish.api.service.role
            - @ezpublish.api.service.content
            - @ezpublish.api.service.content_type
            - @ezpublish.api.service.location
            - @ezpublish.api.service.section
            - @ezpublish.api.repository
